2013-03-14 19:08:30,041 - ubuntuone.SyncDaemon.Main - INFO - Starting Ubuntu One client version 4.0.0
2013-03-14 19:08:30,042 - ubuntuone.SyncDaemon.Main - INFO - Using '/home/ilu/Ubuntu One' as root dir
2013-03-14 19:08:30,042 - ubuntuone.SyncDaemon.Main - INFO - Using '/home/ilu/.local/share/ubuntuone/syncdaemon' as data dir
2013-03-14 19:08:30,042 - ubuntuone.SyncDaemon.Main - INFO - Using '/home/ilu/.local/share/ubuntuone/shares' as shares root dir
2013-03-14 19:08:30,042 - ubuntuone.SyncDaemon.tritcask - INFO - Initializing Tritcask on: /home/ilu/.local/share/ubuntuone/syncdaemon/tritcask
2013-03-14 19:08:30,042 - ubuntuone.SyncDaemon.tritcask - INFO - found 1 data files, 0 dead and 0 broken files
2013-03-14 19:08:30,042 - ubuntuone.SyncDaemon.tritcask - INFO - keydir ready! (keys: 2)
2013-03-14 19:08:30,067 - ubuntuone.SyncDaemon.fsm - INFO - loading updated metadata
2013-03-14 19:08:30,067 - ubuntuone.SyncDaemon.fsm - INFO - initialized: idx_path: 1, idx_node_id: 0, shares: 1
2013-03-14 19:08:30,074 - ubuntuone.SyncDaemon.filesystem_notifications.GeneralProcessor - INFO - Ignoring files: ['\\A#.*\\Z', '\\A.*~\\Z', '\\A.*\\.py[oc]\\Z', '\\A.*\\.sw[nopx]\\Z', '\\A.*\\.swpx\\Z', '\\A\\..*\\.tmp\\Z', '\\A\\.~lock\\..*#\\Z', '\\A\\.goutputstream-.*\\Z', '\\A.*-Spotlight\\Z', '\\A\\.DS_Store\\Z']
2013-03-14 19:08:30,081 - ubuntuone.SyncDaemon.TunnelRunner - INFO - Proxy support not installed.
2013-03-14 19:08:30,082 - ubuntuone.SyncDaemon.HQ - INFO - HashQueue: _hasher started
2013-03-14 19:08:30,523 - ubuntuone.SyncDaemon.DBus - INFO - DBusInterface initialized.
2013-03-14 19:08:30,523 - ubuntuone.SyncDaemon.InteractionInterfaces - INFO - connect: args (<ubuntuone.syncdaemon.interaction_interfaces.SyncdaemonService object at 0xaa1b5ac>,), kwargs {'autoconnecting': True}.
2013-03-14 19:08:30,523 - ubuntuone.SyncDaemon.InteractionInterfaces - INFO - connect: result <generator object connect at 0xaa1e5cc>.
2013-03-14 19:08:30,595 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'INIT'  (queues IDLE  connection 'Not User Not Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 19:08:30,595 - ubuntuone.SyncDaemon.Main - NOTE - Local rescan starting...
2013-03-14 19:08:30,595 - ubuntuone.SyncDaemon.local_rescan - INFO - start scan all volumes
2013-03-14 19:08:30,613 - ubuntuone.SyncDaemon.local_rescan - INFO - processing trash
2013-03-14 19:08:30,614 - ubuntuone.SyncDaemon.local_rescan - INFO - processing move limbo
2013-03-14 19:08:30,614 - ubuntuone.SyncDaemon.InteractionInterfaces - INFO - start: args (<ubuntuone.syncdaemon.interaction_interfaces.SyncdaemonService object at 0xaa1b5ac>,), kwargs {}.
2013-03-14 19:08:30,614 - ubuntuone.SyncDaemon.InteractionInterfaces - INFO - start: result <Deferred at 0xaaa1dec current result: None>.
2013-03-14 19:08:30,614 - ubuntuone.SyncDaemon - INFO - not starting twisted.manhole
2013-03-14 19:08:30,617 - ubuntuone.SyncDaemon.local_rescan - INFO - Ignoring path as it's a symlink: '/home/ilu/Ubuntu One/Shared With Me'
2013-03-14 19:08:30,618 - ubuntuone.SyncDaemon.Main - NOTE - Local rescan finished!
2013-03-14 19:08:30,618 - ubuntuone.SyncDaemon.Main - INFO - hash queue empty. We are ready!
2013-03-14 19:08:31,938 - twisted - ERROR - Unhandled error in Deferred:
2013-03-14 19:08:32,051 - twisted - ERROR - Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 368, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 464, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 551, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1101, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1045, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/ubuntuone-client/ubuntuone/syncdaemon/interaction_interfaces.py", line 1266, in connect
    raise NoAccessToken("got empty credentials.")
ubuntuone.syncdaemon.interaction_interfaces.NoAccessToken: got empty credentials.

2013-03-14 19:23:30,695 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 19:38:30,663 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 19:53:30,633 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 20:08:30,695 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 20:23:30,645 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 20:38:30,695 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 20:53:30,693 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 21:08:30,695 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 21:23:30,694 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 21:38:30,693 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 21:53:30,678 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 22:08:30,694 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 22:23:30,695 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 22:38:30,695 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 22:53:30,694 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 23:08:30,664 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 23:23:30,695 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
2013-03-14 23:38:30,678 - ubuntuone.SyncDaemon.Main - NOTE - ---- MARK (state: <State: 'READY'  (queues IDLE  connection 'Not User With Network')>; queue: 0; offloaded: 0; hash: 0) ----
